final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoe_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoe_2.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoe_3.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Puma Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoe_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Rebok Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoe_5.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
];
